language: node_js
node_js:
  - "0.10"
before_install:
  - git submodule init
  - git submodule update
install:
  - npm install -g bower gulp
  - gem install sass
  - npm install
  - bower install
  - gulp build
  - cd build && python -m SimpleHTTPServer 8001 > /dev/null 2>&1 &
script:
  - gulp ci
