language: node_js
node_js:
  - "0.10"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - git submodule init
  - git submodule update
install:
  - npm install -g bower gulp --quiet
  - npm install --quiet
  - bower install
  - ./node_modules/protractor/bin/webdriver-manager update
script:
  - gulp ci --require coffee-script/register